#!/usr/bin/sh

# n1 is greater
if [ "$1" -gt "$2" ]; then
	n1="$1"
	n2="$2"
else
	n1="$2"
	n2="$1"
fi

n="1"
while [ "$n" -le "$n2" ]; do
	if [ "$((n1 % n))" -eq "0" ] && [ "$((n2 % n))" -eq 0 ]; then
		gcd="$n"
	fi
	n="$(($n + 1))"
done
n="$n1"
found="0"
while [ "$found" = "0" ]; do
	if [ "$((n % n1))" -eq "0" ] && [ "$((n % n2))" -eq "0" ]; then
		lcm="$n"
		found="1"
	fi
	n="$(($n + 1))"
done
echo "GCD = $gcd, LCM = $lcm"
