#!/bin/csh

while (1)
    echo "Are you OK?"
    set response = $<

    if ($response == "y" || $response == "Y") then
        echo "glad to hear it"
        break
    else if ($response == "n" || $response == "N") then
        echo "sorry that you are not feeling good"
        break
    else
        echo "incorrect choice"
    endif
end
