#!/bin/csh

if ($#argv != 2) then
    echo "Enter two integers"
    exit 1
endif

set a = $1
set b = $2
set smaller = ($a < $b) ? $a : $b

set gcd = 1
@ i = 1
while ($i <= $smaller)
    if (($a % $i == 0) && ($b % $i == 0)) then
        @ gcd = $i
    endif
    @ i++
end

@ lcm = ($a * $b) / $gcd

echo "GCD $gcd"
echo "LCM $lcm"