#!/bin/csh
set days = (Monday Tuesday Wednesday Thursday Friday Saturday Sunday)
set i = 1
while ($i <= $#days)
	set j = $i
	while ($j <= $#days)
		echo -n "$days[$j] "
		@ j++
	@ i++
	echo ""
	end
end